### ISSUE TITLE
v5/5.0.1 not launching

### ISSUE THREAD

**Issue by ghost** [Shadsterwolf/BotWUnpacker#11]
After unzipping the contents of both versions and attempting to run them, nothing happens. V3.1.1 works fine. Is there something I am missing? I have .Net 5 installed.

**Comment by jackwaecow** [comment]
same

**Comment by Shadsterwolf** [comment]
Apologies for not following up on this. As the new Zelda game approaches, I've taken some time to look at this.
It basically turns out that there's a ton of conflicts of just old code and old nuget packages that doesn't support .Net 5/6

I've deleted the pre-release of .Net 5 builds and will work on updating it to .Net 6 instead.
I don't know when I'll get this done as there's lots of trash code to clean up.
