### ISSUE TITLE
[Question] How did you make your yaz0 implementation so much better than libyaz0/wszst?

### ISSUE THREAD

**Issue by ghost** [Shadsterwolf/BotWUnpacker#5]
The main thing I still use BotwUnpacker for is it's great yaz0 encoding. It's not only far faster than wszst/libyaz0's `-level 9` compression, it makes the files as small as they were originally.

How did you accomplish this? What is wszst/libyaz0 doing wrong with their `-level 9` compression that makes them end up with slightly larger files?

**Comment by Shadsterwolf** [comment]
I'm quite a scrub when it comes to explaining how compression works (or any code for that matter), since this is basically my first time making something like this. I'm no Python programmer either, just am able to read it enough to understand the logic.

I researched Yaz0's encoding for a long time, and even then still has some rules I'm missing.

Nintendo's compression appears to always be at it's best so I don't understand the need for how good the compression is (idk what even level 9 does in this context). What I believe **MOST Yaz0 encoders forget is the PREDICTION rule** portion where you need one step to check ahead. While running your initial stage of checking how much space you'd save, you need to compare if the next cluster of bytes over will save even more space! 
`//flag the next byte as straight copy because the next one will solve one copy instead of two. (End up using 3 bytes instead of 4)`
It was fun learning how well Nintendo compresses their data.
